---
title: "Forest Sliver Check"
author: "SCS-Global"
date: "2024-03-19"
output: 
  html_document:
    toc: TRUE
    toc_depth: 5
    df_print: tibble
    keep_html: TRUE

always_allow_html: true
---

```{r setup, include=FALSE, message = FALSE, warning=FALSE, error=FALSE, cache=TRUE}
library(readxl)
library(magrittr)
library(janitor)
library(ggplot2)
library(dplyr)
library(RColorBrewer)
library(psych)
library(tmap)
library(useful)
library(caret)
library(tibble)
library(DescTools)
library(animation)
library(ModelMetrics)
library(knitr)
library(kableExtra)
library(rmarkdown)
library(dataMaid)
library(animation)
library(sf)
library(tmap)
library(basemaps)
library(htmltools)
library(gtsummary)
library(data.table)
library(htmltools)
library(latex2exp)
options(htmltools.dir.version = FALSE, htmltools.preserve.raw = FALSE)
knitr::opts_chunk$set(
  echo = TRUE, message = FALSE, warning = FALSE,
  error = FALSE, comment = NA, tidy.opts = list(width.cutoff = 60), tidy = "styler"
)
```

## Forest Sliver Check

***Workflow for Checking Minimum Size of Forest Patches in LULC Maps***

```{r}
tmap_mode("view")
tmap_options(check.and.fix = T)
polygon = read_sf("~/git_repos/forest-sliver-check/data/LULC_RR_2009_Dissolved.shp")
multipolygon = st_cast(polygon, "MULTIPOLYGON")
  tm_shape(st_geometry(multipolygon)) + 
  tm_borders(col = "red") + 
  tm_grid() +
    tm_basemap('Esri.WorldImagery') + 
    tm_layout(main.title = "Fig 1: Polygonized LULC Raster Submitted by Client", 
            title.size = 1.5, main.title.position = "center")
```

```{r, eval=FALSE}
multipolygon$area = st_area(multipolygon)
slivers = multipolygon %>%
  dplyr::filter(as.numeric(area) < 50000)
multipolygon$area
```

```{r, eval=FALSE}
st_write(slivers, "slivers.shp")
```

```{r, eval=FALSE}
tmap_mode("view")
tm_shape(st_geometry(slivers)) + tm_polygons()
```
